services:
  frontend:
    build: frontend/surveys
    mem_limit: 1g

    ports:
      - "4200:4200"
    
    environment:
      - API_URL=http://api_surveys:8080

    restart: always
    depends_on:
      api_surveys:
        condition: service_started


  api_surveys:
    build: backend/surveys
    mem_limit: 300mb
    ports:
      - "8080:8080"
    
    environment:
      DB_URL: jdbc:mysql://db_surveys:3306/surveys?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
    
    restart: always
    depends_on:
      db_surveys:
        condition: service_healthy
  
  db_surveys:
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: surveys
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 10
